import type {
  CircumlocutionTask,
  SurvivalScenarioTask,
} from "@/types/survival-speaking";

export const SEED_CIRCUMLOCUTION_TASKS: CircumlocutionTask[] = [
  {
    id: "circ_microwave",
    targetWord: "microwave",
    forbiddenWords: ["microwave", "micro"],
    tabooLemmas: ["microwave", "microwaves", "microwaving", "microwaved"],
    vietnameseMeaning: "Lò vi sóng",
    category: "Đồ gia dụng (Kitchen Appliance)",
    genus: "a kitchen appliance",
    differentia: "heats up food and drinks quickly using electromagnetic waves",
    semanticKeyAnchors: ["heat", "food", "kitchen", "quick", "warm"],
    difficulty: "easy",
    timeLimitSeconds: 5,
    hints: {
      functionHint: "Dùng để hâm nóng thức ăn cực nhanh bằng sóng",
      categoryHint: "Một thiết bị điện tử trong nhà bếp (Kitchen appliance)",
      contextHint: "Thường đặt trên kệ bếp trong nhà hoặc văn phòng",
      starterHint: "It's a kitchen machine that you use to heat up food quickly.",
    },
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Tự diễn giải trong 5 giây mà không dùng từ cấm." },
      { tier: 1, title: "Chức năng (Function)", content: "Dùng để hâm nóng thức ăn cực nhanh bằng sóng vi ba." },
      { tier: 2, title: "Chủng loại & Vị trí", content: "Một thiết bị điện tử nhà bếp (kitchen appliance), đặt trên kệ hoặc văn phòng." },
      { tier: 3, title: "Khung câu mở đầu", content: "It's a kind of electrical appliance in the kitchen that you use to ______ ." },
      { tier: 4, title: "Câu diễn giải mẫu", content: "It's a kitchen appliance that you use to heat up cold food or drinks in just a couple of minutes." },
    ],
    sampleExplanations: [
      "It's a kitchen appliance that you use to heat up cold food or drinks in just a couple of minutes.",
      "It's an electrical box in the kitchen that warms up your meal quickly.",
    ],
    suggestedVocabulary: [
      { term: "a kind of appliance", meaningVi: "một loại thiết bị gia dụng", partOfSpeech: "phrase" },
      { term: "used for heating up", meaningVi: "được dùng để hâm nóng", partOfSpeech: "phrase" },
      { term: "found in the kitchen", meaningVi: "thường thấy trong nhà bếp", partOfSpeech: "phrase" },
    ],
  },
  {
    id: "circ_umbrella",
    targetWord: "umbrella",
    forbiddenWords: ["umbrella", "raincoat"],
    tabooLemmas: ["umbrella", "umbrellas"],
    vietnameseMeaning: "Cây dù / Cây ô",
    category: "Vật dụng hàng ngày (Daily Object)",
    genus: "a handheld protective object",
    differentia: "protects you from rain or sunlight and can be folded",
    semanticKeyAnchors: ["rain", "protect", "hold", "wet", "head"],
    difficulty: "easy",
    timeLimitSeconds: 5,
    hints: {
      functionHint: "Dùng để che mưa hoặc che nắng khi đi ngoài đường",
      categoryHint: "Một vật dụng cầm tay có thể mở ra và gập lại",
      contextHint: "Mang theo khi dự báo thời tiết có mưa",
      starterHint: "It's a handheld object that protects you from rain or sunlight.",
    },
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Tự diễn giải trong 5 giây." },
      { tier: 1, title: "Chức năng (Function)", content: "Dùng để che mưa hoặc che nắng khi đi ngoài trời." },
      { tier: 2, title: "Chủng loại & Cấu tạo", content: "Vật dụng cầm tay có vải chống nước, có thể mở bung ra và gấp gọn lại." },
      { tier: 3, title: "Khung câu mở đầu", content: "It's something you hold above your head when it's ______ so you don't get ______ ." },
      { tier: 4, title: "Câu diễn giải mẫu", content: "It's something you hold above your head when it's raining so you don't get wet." },
    ],
    sampleExplanations: [
      "It's something you hold above your head when it's raining so you don't get wet.",
      "It's a foldable item with a handle that protects you from rain.",
    ],
    suggestedVocabulary: [
      { term: "hold above your head", meaningVi: "cầm giương lên trên đầu", partOfSpeech: "phrase" },
      { term: "protects you from rain", meaningVi: "bảo vệ bạn khỏi nước mưa", partOfSpeech: "phrase" },
      { term: "foldable item", meaningVi: "vật dụng có thể gấp gọn", partOfSpeech: "phrase" },
    ],
  },
  {
    id: "circ_subscription",
    targetWord: "subscription",
    forbiddenWords: ["subscription", "subscribe"],
    tabooLemmas: ["subscription", "subscriptions", "subscribe", "subscribing", "subscribed"],
    vietnameseMeaning: "Gói đăng ký định kỳ (Netflix, Spotify...)",
    category: "Dịch vụ số (Digital Service)",
    genus: "a payment arrangement",
    differentia: "pays a recurring monthly or annual fee for continuous access to digital media",
    semanticKeyAnchors: ["pay", "monthly", "fee", "service", "access"],
    difficulty: "medium",
    timeLimitSeconds: 5,
    hints: {
      functionHint: "Thanh toán một khoản tiền định kỳ hàng tháng để sử dụng dịch vụ",
      categoryHint: "Mô hình thanh toán định kỳ",
      contextHint: "Thường thấy ở Netflix, Spotify, ứng dụng phần mềm",
      starterHint: "It's an agreement where you pay a monthly fee to access a service.",
    },
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Tự diễn giải trong 5 giây." },
      { tier: 1, title: "Bản chất", content: "Thanh toán định kỳ hàng tháng/năm để duy trì quyền truy cập dịch vụ." },
      { tier: 2, title: "Bối cảnh thực tế", content: "Rất phổ biến với Netflix, Spotify, hoặc ứng dụng xem phim trực tuyến." },
      { tier: 3, title: "Khung câu mở đầu", content: "It's when you pay a monthly fee to keep access to ______ ." },
      { tier: 4, title: "Câu diễn giải mẫu", content: "It's when you pay an amount of money every month to continue using a service like Netflix or Spotify." },
    ],
    sampleExplanations: [
      "It's when you pay an amount of money every month to continue using a service like Netflix or Spotify.",
      "It's a recurring payment plan for continuous access to an app.",
    ],
    suggestedVocabulary: [
      { term: "recurring payment", meaningVi: "thanh toán định kỳ lặp lại", partOfSpeech: "phrase" },
      { term: "monthly fee", meaningVi: "phí hàng tháng", partOfSpeech: "phrase" },
      { term: "continuous access", meaningVi: "quyền truy cập liên tục", partOfSpeech: "phrase" },
    ],
  },
  {
    id: "circ_algorithm",
    targetWord: "algorithm",
    forbiddenWords: ["algorithm", "code"],
    tabooLemmas: ["algorithm", "algorithms", "algorithmic"],
    vietnameseMeaning: "Thuật toán máy tính",
    category: "Công nghệ (Technology & Math)",
    genus: "a computational procedure",
    differentia: "a set of step-by-step instructions that computers execute to solve problems or recommend feeds",
    semanticKeyAnchors: ["step-by-step", "rules", "computer", "solve", "recommend"],
    difficulty: "hard",
    timeLimitSeconds: 5,
    hints: {
      functionHint: "Một tập hợp các quy tắc từng bước để máy tính giải quyết vấn đề",
      categoryHint: "Quy trình tính toán toán học/lập trình",
      contextHint: "Quyết định video nào xuất hiện trên TikTok hoặc YouTube của bạn",
      starterHint: "It's a set of step-by-step mathematical rules that a computer follows.",
    },
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Tự diễn giải trong 5 giây." },
      { tier: 1, title: "Bản chất", content: "Một chuỗi các chỉ dẫn logic từng bước để máy tính xử lý dữ liệu." },
      { tier: 2, title: "Ứng dụng đời thực", content: "Cơ chế quyết định nội dung đề xuất trên YouTube, TikTok hoặc Google Search." },
      { tier: 3, title: "Khung câu mở đầu", content: "It's a set of step-by-step mathematical rules that a computer ______ to ______ ." },
      { tier: 4, title: "Câu diễn giải mẫu", content: "It's a set of step-by-step instructions that computers use to solve problems or recommend content." },
    ],
    sampleExplanations: [
      "It's a set of step-by-step instructions that computers use to solve problems or recommend videos.",
      "It's mathematical logic that determines what you see on social media feeds.",
    ],
    suggestedVocabulary: [
      { term: "step-by-step rules", meaningVi: "các quy tắc từng bước một", partOfSpeech: "phrase" },
      { term: "recommend content", meaningVi: "gợi ý nội dung đề xuất", partOfSpeech: "phrase" },
      { term: "process data", meaningVi: "xử lý dữ liệu", partOfSpeech: "phrase" },
    ],
  },
];

export const SEED_SURVIVAL_SCENARIOS: SurvivalScenarioTask[] = [
  {
    id: "scen_interview_fast",
    context: "job_interview",
    contextTitleVi: "Phỏng vấn xin việc (Job Interview)",
    problemDescriptionVi: "Người phỏng vấn nói rất nhanh một thuật ngữ chuyên ngành phức tạp mà bạn chưa kịp nghe rõ.",
    audioPromptText: "Could you elaborate on how your algorithmic optimization reduced backend latency?",
    recommendedSkill: "asking_repetition",
    suggestedRepairPhrases: [
      "Sorry, could you say that again a little more slowly?",
      "I didn't quite catch the last part. Could you repeat that, please?",
    ],
    timeLimitSeconds: 5,
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Phản xạ cứu cánh ngay lập tức." },
      { tier: 1, title: "Chiến lược xử lý", content: "Lịch sự xin người phỏng vấn nhắc lại câu hỏi với tốc độ chậm hơn một chút." },
      { tier: 2, title: "Cụm từ cứu cánh", content: "Sorry, could you repeat that / I didn't quite catch that..." },
      { tier: 3, title: "Khung câu ứng biến", content: "Sorry, could you say that again ______ because ______ ?" },
      { tier: 4, title: "Câu mẫu chuẩn bản xứ", content: "I'm sorry, I didn't quite catch the last part. Could you say that again a little more slowly?" },
    ],
    suggestedVocabulary: [
      { term: "I didn't quite catch that", meaningVi: "Tôi chưa nghe kịp phần đó", partOfSpeech: "phrase" },
      { term: "say that again slowly", meaningVi: "nói lại chậm hơn một chút", partOfSpeech: "phrase" },
      { term: "could you elaborate", meaningVi: "bạn có thể giải thích chi tiết hơn", partOfSpeech: "phrase" },
    ],
  },
  {
    id: "scen_workplace_thinking",
    context: "workplace_meeting",
    contextTitleVi: "Cuộc họp công ty (Workplace Meeting)",
    problemDescriptionVi: "Sếp bất ngờ hỏi quan điểm của bạn về chiến lược quý tới và bạn cần 3-5 giây để suy nghĩ.",
    audioPromptText: "What are your thoughts on our proposed Q3 marketing budget allocation?",
    recommendedSkill: "buying_time",
    suggestedRepairPhrases: [
      "That's a very interesting question. Let me think for a second...",
      "Well, to be honest, let me see how we should approach this...",
    ],
    timeLimitSeconds: 5,
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Phản xạ mua thời gian ngay." },
      { tier: 1, title: "Chiến lược xử lý", content: "Dùng cụm đệm khen câu hỏi hay hoặc xin 2-3 giây suy nghĩ thay vì ngồi im lặng." },
      { tier: 2, title: "Cụm từ cứu cánh", content: "That's a great question. Let me think for a moment..." },
      { tier: 3, title: "Khung câu ứng biến", content: "That's a very interesting point. Off the top of my head, ______ ." },
      { tier: 4, title: "Câu mẫu chuẩn bản xứ", content: "That's a really interesting question. Let me think for just a second on how to frame this." },
    ],
    suggestedVocabulary: [
      { term: "let me think for a second", meaningVi: "cho tôi suy nghĩ một giây", partOfSpeech: "phrase" },
      { term: "off the top of my head", meaningVi: "theo suy nghĩ ngay lúc này", partOfSpeech: "phrase" },
      { term: "to be completely honest", meaningVi: "thành thật mà nói", partOfSpeech: "phrase" },
    ],
  },
  {
    id: "scen_misunderstanding_restaurant",
    context: "restaurant",
    contextTitleVi: "Nhà hàng (Restaurant)",
    problemDescriptionVi: "Bồi bàn tưởng bạn muốn hủy toàn bộ đơn hàng nhưng bạn chỉ muốn đổi món khai vị.",
    audioPromptText: "So you would like to cancel your entire order, right?",
    recommendedSkill: "misunderstanding_recovery",
    suggestedRepairPhrases: [
      "No, sorry, what I meant was I only want to change the appetizer, not cancel everything.",
      "That's not exactly what I meant. I just want to switch the soup to a salad.",
    ],
    timeLimitSeconds: 5,
    tierHints: [
      { tier: 0, title: "Không gợi ý", content: "Đính chính sự hiểu nhầm ngay." },
      { tier: 1, title: "Chiến lược xử lý", content: "Dùng mẫu đính chính lịch sự 'What I meant was...' để giải tỏa hiểu nhầm." },
      { tier: 2, title: "Cụm từ cứu cánh", content: "That's not quite what I meant / What I actually meant was..." },
      { tier: 3, title: "Khung câu ứng biến", content: "Oh sorry, that's not what I meant. I only wanted to ______ ." },
      { tier: 4, title: "Câu mẫu chuẩn bản xứ", content: "Oh sorry, that's not quite what I meant. I just want to change the appetizer, not cancel the entire meal." },
    ],
    suggestedVocabulary: [
      { term: "that's not what I meant", meaningVi: "đó không phải là ý tôi muốn nói", partOfSpeech: "phrase" },
      { term: "what I actually meant was", meaningVi: "điều tôi thực sự muốn nói là", partOfSpeech: "phrase" },
      { term: "switch A to B", meaningVi: "đổi từ A sang B", partOfSpeech: "phrase" },
    ],
  },
];
