import type { SpokenWordItem } from "@/types/vocabulary-context";

export const INITIAL_DEFAULT_WORD: SpokenWordItem = {
  id: "lex_decision",
  word: "decision",
  ipaUS: "/dɪˈsɪʒ.ən/",
  ipaUK: "/dɪˈsɪʒ.ən/",
  partOfSpeech: "noun",
  cefrLevel: "B1",
  meaningVi: "Quyết định, sự phán quyết",
  englishDefinition: "A choice that you make about something after thinking about several possibilities.",
  stressedSyllableIndex: 2,
  stressExplanationVi: "Trọng âm rơi vào âm tiết thứ hai: de-CI-sion (/ˈsɪʒ/).",
  endingSoundGuideVi: "Bật âm đuôi /ʒ.ən/ nhẹ nhàng, rung nhẹ vòm miệng, không phát âm thành 'sơn'.",
  collocations: [
    {
      phrase: "make a decision",
      meaningVi: "đưa ra một quyết định",
      exampleSentence: "We have to make a tough decision today.",
      collocationType: "verb_noun",
      pmiStrength: "native_chunk",
    },
    {
      phrase: "reach a decision",
      meaningVi: "đi đến quyết định thống nhất",
      exampleSentence: "The committee finally reached a decision after two hours.",
      collocationType: "verb_noun",
      pmiStrength: "high",
    },
    {
      phrase: "informed decision",
      meaningVi: "quyết định sáng suốt, có cơ sở dữ liệu",
      exampleSentence: "Take your time so you can make an informed decision.",
      collocationType: "adj_noun",
      pmiStrength: "high",
    },
  ],
  contextSentences: [
    {
      id: "s1_decision",
      domain: "workplace",
      domainTitleVi: "Công việc & Giao tiếp (Workplace)",
      sentenceEn: "We need to consider this decision carefully before the team meeting.",
      sentenceVi: "Chúng ta cần cân nhắc quyết định này thật kỹ trước cuộc họp nhóm.",
      targetWordHighlighted: "decision",
      linkingSoundHints: "need to -> need-tuh | this decision -> this-decision",
      rhythmNoteVi: "Nhấn mạnh từ 'decision' và 'carefully'.",
    },
    {
      id: "s2_decision",
      domain: "opinions",
      domainTitleVi: "Bày tỏ quan điểm (Opinions)",
      sentenceEn: "In my opinion, making a quick decision is better than waiting.",
      sentenceVi: "Theo quan điểm của tôi, đưa ra quyết định nhanh còn tốt hơn là cứ chờ đợi.",
      targetWordHighlighted: "decision",
      linkingSoundHints: "in my -> in-my | than waiting -> thun-waiting",
      rhythmNoteVi: "Nhấn 'opinion', 'quick decision', 'better'.",
    },
  ],
  spontaneousChallenge: {
    promptEn: "Your teammate asks whether the project scope should change. Reply in 1-2 spoken sentences using 'decision'.",
    promptVi: "Đồng nghiệp hỏi bạn liệu có nên thay đổi phạm vi dự án không. Hãy tự nói 1-2 câu phản xạ có chứa từ 'decision'.",
    targetCollocation: "make a decision",
    suggestedOpeningEn: "I think we should discuss this with the client before making a final decision...",
  },
  wordMasteryScore: 0,
  sentenceMasteryScore: 0,
  isMastered: false,
  practiceCount: 0,
};
