import type { ChunkRecord } from "@/types/chunk-automaticity";

export const SEED_CHUNK_LIBRARY: ChunkRecord[] = [
  {
    id: "chunk_depend_on",
    familyKey: "depend_on_conditional",
    canonicalChunk: "It depends on...",
    meaningVi: "Điều này còn phụ thuộc vào...",
    type: "sentence_frame",
    difficulty: 3,
    functionName: "Conditional Decision",
    variants: [
      { id: "v1", expression: "That really depends on...", register: "neutral", exampleSentence: "That really depends on your budget." },
      { id: "v2", expression: "It depends whether...", register: "formal", exampleSentence: "It depends whether we finish on time." },
      { id: "v3", expression: "It mostly depends on...", register: "casual", exampleSentence: "It mostly depends on the weather." },
    ],
    exampleSentences: [
      "It depends on how much free time you have.",
      "Whether we go out depends on the traffic.",
    ],
    masteryScore: 72,
    retrievalLatencyMs: 1800,
    stage: "contextual_use",
    practiceCount: 8,
    successCount: 6,
    independentSuccessCount: 5,
  },
  {
    id: "chunk_to_be_honest",
    familyKey: "to_be_honest_stance",
    canonicalChunk: "To be honest, ...",
    meaningVi: "Thành thật mà nói thì...",
    type: "conversation_opener",
    difficulty: 2,
    functionName: "Expressing Stance",
    variants: [
      { id: "v1", expression: "Honestly speaking, ...", register: "neutral", exampleSentence: "Honestly speaking, I prefer tea." },
      { id: "v2", expression: "Truth be told, ...", register: "formal", exampleSentence: "Truth be told, we need more time." },
    ],
    exampleSentences: [
      "To be honest, I didn't like the meeting.",
      "To be honest, that's not my favorite topic.",
    ],
    masteryScore: 85,
    retrievalLatencyMs: 1400,
    stage: "automaticity",
    practiceCount: 12,
    successCount: 11,
    independentSuccessCount: 10,
  },
  {
    id: "chunk_the_main_reason",
    familyKey: "the_main_reason_cause",
    canonicalChunk: "The main reason is that...",
    meaningVi: "Lý do chính là vì...",
    type: "sentence_frame",
    difficulty: 3,
    functionName: "Giving Reason",
    variants: [
      { id: "v1", expression: "The primary reason is because...", register: "formal", exampleSentence: "The primary reason is because of safety." },
      { id: "v2", expression: "Mostly because...", register: "casual", exampleSentence: "Mostly because I'm busy." },
    ],
    exampleSentences: [
      "The main reason is that it saves a lot of travel time.",
      "The main reason is that I enjoy working independently.",
    ],
    masteryScore: 65,
    retrievalLatencyMs: 2400,
    stage: "spoken_recall",
    practiceCount: 6,
    successCount: 4,
    independentSuccessCount: 3,
  },
  {
    id: "chunk_for_example",
    familyKey: "for_example_elaboration",
    canonicalChunk: "For example, ...",
    meaningVi: "Ví dụ như...",
    type: "example_giving",
    difficulty: 2,
    functionName: "Giving Illustration",
    variants: [
      { id: "v1", expression: "For instance, ...", register: "formal", exampleSentence: "For instance, last week we had a test." },
      { id: "v2", expression: "Take ... as an example", register: "neutral", exampleSentence: "Take remote work as an example." },
    ],
    exampleSentences: [
      "For example, you can take an online course.",
      "For example, yesterday I walked 5 kilometers.",
    ],
    masteryScore: 90,
    retrievalLatencyMs: 1200,
    stage: "automaticity",
    practiceCount: 15,
    successCount: 14,
    independentSuccessCount: 14,
  },
];
